name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest

    steps:
      - name: Install requirements
        working-directory: ./
        run: pip install -r requirements.txt

      - name: Run pylint
        working-directory: ./
        run: |
          pip install pylint
          pylint nautilus_nlp tests

      - name: Run pytest
        working-directory: ./
        run: |
          pip install pytest
          pytest tests
